apiVersion: apps/v1
kind: Deployment
metadata:
  name: tx-k8s-acceptance
  labels:
    app: tx-k8s-acceptance
spec:
  replicas: 3
  selector:
    matchLabels:
       app: tx-k8s-acceptance
  template:
    metadata:
      labels:
        app: tx-k8s-acceptance
    spec:
      containers:
      - name: tx-k8s
        image: tx_k8s:v2

